//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string UserIdNo { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> UserDateOfAdd { get; set; }
        public string UserAdress1 { get; set; }
        public string UserAdress2 { get; set; }
        public string UserCity { get; set; }
        public string UserDistrict { get; set; }
    }
}
